name: Update Docker image

on:
  repository_dispatch:
    types:
      - gem-released

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.4

      - name: Configure git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Update gems
        run: script/workflow/update-gems.sh
        env:
          RELEASED_GEM_NAME: '${{ github.event.client_payload.name }}'
          RELEASED_GEM_VERSION: '${{ github.event.client_payload.version }}'

      - name: Detect changes
        run: script/workflow/detect-changes.sh

      - name: Unit tests
        run: |
          bundle install
          bundle exec rake spec

      - name: Login to Docker Hub
        run: script/workflow/docker-login.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t pactfoundation/pact-broker:latest .

      - name: Integration tests
        run: script/test.sh

      - name: Calculate next tag
        run: echo "::set-env name=TAG::$(script/release/next-docker-tag.sh)"

      - name: Set major tag
        run: echo "::set-env name=MAJOR_TAG::$(echo $TAG | cut -d'.' -f1)"

      - name: Commit and push
        run: |
          script/workflow/git-commit-and-push.sh
          echo "::set-env name=GIT_TAG_PUSHED::true"
        env:
          RELEASED_GEM_NAME: '${{ github.event.client_payload.name }}'
          RELEASED_GEM_VERSION: '${{ github.event.client_payload.version }}'

      - name: Push image to Docker Hub
        run: |
          docker tag pactfoundation/pact-broker:latest pactfoundation/pact-broker:${TAG}
          docker tag pactfoundation/pact-broker:latest pactfoundation/pact-broker:${MAJOR_TAG}
          docker push pactfoundation/pact-broker:latest
          docker push pactfoundation/pact-broker:${TAG}
          docker push pactfoundation/pact-broker:${MAJOR_TAG}
